server:
  port: 8081
spring:
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml
  thymeleaf:
    mode: HTML
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    urL:
    username:
    password:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    default-property-inclusion: non_null

mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
  global-config:
    db-config:
      logic-delete-value: true
      logic-not-delete-value: false
      table-prefix: t_
      id-type: uuid

polo:
  ip-get-url: http://ip.taobao.com/service/getIpInfo.php?ip=%s
  local-ips: 127.0.0.1,0:0:0:0:0:0:0:1
